/** Static demo profile — replace with API / DB data later. */
export const PROFILE_DEMO = {
  displayName: "Umar Javed",
  roleTitle: "Frontend Developer",
  avatarSrc: "/avatar.png",
  avatarFallback: "UJ",
  headlineSkills: ["React", "Next.js", "TypeScript"],
  email: "umar@example.com",
  location: "Lahore, Pakistan",
  university: "UMT Lahore",
  username: "umarjaved",
  bio: "I am a frontend developer passionate about building clean, modern, and user-friendly web applications.",
  degree: "Software Engineering",
  semester: "4th Semester",
  experienceLevel: "Intermediate",
  experienceValue: "intermediate" as const,
  githubUrl: "https://github.com/username",
  linkedinUrl: "https://linkedin.com/in/username",
  portfolioUrl: "https://yourportfolio.com",
  skills: [
    "HTML",
    "CSS",
    "JavaScript",
    "TypeScript",
    "React",
    "Next.js",
    "Tailwind CSS",
    "Node.js",
  ],
} as const;
